"""Canonical unit conversion and translation-table access."""

from .conversion import (
    UnitConversionError,
    UnitTransform,
    accepted_units,
    conversion_trace,
    convert_delta,
    convert_value,
    resolve_unit,
    unit_translation_table,
    unit_translation_table_sha256,
)
from .property_response import (
    DIRECT_PRESENTATION,
    DIFFERENCE_PRESENTATION,
    PURE_COMPONENTS_SAME_PROPORTION,
    PURE_SOLUTE_SAME_STATE,
    PURE_SOLVENT_SAME_STATE,
    RATIO_PRESENTATION,
    RELATIVE_DIFFERENCE_PRESENTATION,
    TEMPERATURE_DIFFERENCE_PRESENTATION,
    PresentationKind,
    classify_presentation,
    materialize_reported_response,
    presentation_requires_reference,
    reference_component_num_ids,
    reported_canonical_unit,
)

__all__ = [
    "UnitConversionError",
    "UnitTransform",
    "accepted_units",
    "conversion_trace",
    "convert_delta",
    "convert_value",
    "resolve_unit",
    "unit_translation_table",
    "unit_translation_table_sha256",
    "DIRECT_PRESENTATION",
    "DIFFERENCE_PRESENTATION",
    "PURE_COMPONENTS_SAME_PROPORTION",
    "PURE_SOLUTE_SAME_STATE",
    "PURE_SOLVENT_SAME_STATE",
    "RATIO_PRESENTATION",
    "RELATIVE_DIFFERENCE_PRESENTATION",
    "TEMPERATURE_DIFFERENCE_PRESENTATION",
    "PresentationKind",
    "classify_presentation",
    "materialize_reported_response",
    "presentation_requires_reference",
    "reference_component_num_ids",
    "reported_canonical_unit",
]
