"""
Property name aliases.

Maps common shorthand, symbols, and alternate phrasings to the canonical
``prop_id`` stored in property_ids.csv.  All keys are lowercase.
"""

# alias (lowercase) → canonical prop_id
PROP_ALIASES: dict[str, str] = {
    # ── Density / volumetric ─────────────────────────────────────
    "density":                  "mass_density_kg_m3",
    "rho":                      "mass_density_kg_m3",
    "mass density":             "mass_density_kg_m3",
    "specific volume":          "specific_volume_m3_kg",
    "molar volume":             "molar_volume_m3_mol",
    "vm":                       "molar_volume_m3_mol",
    "excess volume":            "excess_molar_volume_m3_mol",
    "excess molar volume":      "excess_molar_volume_m3_mol",
    "ve":                       "excess_molar_volume_m3_mol",
    "vex":                      "excess_molar_volume_m3_mol",
    "apparent molar volume":    "apparent_molar_volume_m3_mol",
    "partial molar volume":     "partial_molar_volume_m3_mol_{DOIcomp_id}",
    "expansion coefficient":    "isobaric_coefficient_of_expansion_1_k",
    "alpha_p":                  "isobaric_coefficient_of_expansion_1_k",
    "isothermal compressibility": "isothermal_compressibility_1_kpa",
    "kappa_t":                  "isothermal_compressibility_1_kpa",
    "compressibility factor":   "compressibility_factor",
    "z":                        "compressibility_factor",
    "amount density":           "amount_density_mol_m3",
    "molar concentration":      "amount_density_mol_m3",
    "critical density":         "critical_density_kg_m3",
    "critical molar volume":    "critical_molar_volume_m3_mol",
    "b2":                       "2nd_virial_coefficient_m3_mol",
    "second virial coefficient":"2nd_virial_coefficient_m3_mol",
    "2nd virial coefficient":   "2nd_virial_coefficient_m3_mol",
    "b3":                       "3rd_virial_coefficient_m6_mol2",
    "third virial coefficient": "3rd_virial_coefficient_m6_mol2",
    "3rd virial coefficient":   "3rd_virial_coefficient_m6_mol2",
    "thermal pressure coefficient": "thermal_pressure_coefficient_kpa_k",
    # ── Viscosity / transport ────────────────────────────────────
    "viscosity":                "viscosity_pa_s",
    "eta":                      "viscosity_pa_s",
    "dynamic viscosity":        "viscosity_pa_s",
    "kinematic viscosity":      "kinematic_viscosity_m2_s",
    "nu":                       "kinematic_viscosity_m2_s",
    "diffusion coefficient":    "binary_diffusion_coefficient_m2_s",
    "binary diffusion":         "binary_diffusion_coefficient_m2_s",
    "d12":                      "binary_diffusion_coefficient_m2_s",
    "self diffusion":           "self_diffusion_coefficient_m2_s",
    "self diffusion coefficient": "self_diffusion_coefficient_m2_s",
    "tracer diffusion":         "tracer_diffusion_coefficient_m2_s_{DOIcomp_id}",
    "thermal conductivity":     "thermal_conductivity_w_m_k",
    "lambda":                   "thermal_conductivity_w_m_k",
    "thermal diffusivity":      "thermal_diffusivity_m2_s",
    "electrical conductivity":  "electrical_conductivity_s_m",
    "conductivity":             "electrical_conductivity_s_m",
    "molar conductivity":       "molar_conductivity_s_m2_mol",
    # ── Heat capacity / enthalpy ────────────────────────────────
    "heat capacity":            "molar_heat_capacity_at_constant_pressure_j_k_mol",
    "cp":                       "molar_heat_capacity_at_constant_pressure_j_k_mol",
    "c_p":                      "molar_heat_capacity_at_constant_pressure_j_k_mol",
    "molar heat capacity":      "molar_heat_capacity_at_constant_pressure_j_k_mol",
    "isobaric heat capacity":   "molar_heat_capacity_at_constant_pressure_j_k_mol",
    "cv":                       "molar_heat_capacity_at_constant_volume_j_k_mol",
    "c_v":                      "molar_heat_capacity_at_constant_volume_j_k_mol",
    "isochoric heat capacity":  "molar_heat_capacity_at_constant_volume_j_k_mol",
    "specific heat":            "specific_heat_capacity_at_constant_pressure_j_k_kg",
    "saturation heat capacity": "molar_heat_capacity_at_saturation_pressure_j_k_mol",
    "c_sat":                    "molar_heat_capacity_at_saturation_pressure_j_k_mol",
    "molar enthalpy":           "molar_enthalpy_kj_mol",
    "enthalpy":                 "molar_enthalpy_kj_mol",
    "hm":                       "molar_enthalpy_kj_mol",
    "molar entropy":            "molar_entropy_j_k_mol",
    "entropy":                  "molar_entropy_j_k_mol",
    "sm":                       "molar_entropy_j_k_mol",
    "joule-thomson coefficient": "joulethomson_coefficient_k_kpa",
    "joule-thomson":            "joulethomson_coefficient_k_kpa",
    "mu_jt":                    "joulethomson_coefficient_k_kpa",
    "apparent molar heat capacity": "apparent_molar_heat_capacity_j_k_mol",
    "excess heat capacity":     "excess_molar_heat_capacity_j_k_mol",
    "cpex":                     "excess_molar_heat_capacity_j_k_mol",
    "heat capacity per volume": "heat_capacity_at_constant_pressure_per_volume_j_k_m3",
    # ── Phase equilibrium / VLE ──────────────────────────────────
    "vapor pressure":           "vapor_or_sublimation_pressure_kpa",
    "vapour pressure":          "vapor_or_sublimation_pressure_kpa",
    "sublimation pressure":     "vapor_or_sublimation_pressure_kpa",
    "pvap":                     "vapor_or_sublimation_pressure_kpa",
    "boiling point":            "boiling_temperature_at_pressure_p_k",
    "boiling temperature":      "boiling_temperature_at_pressure_p_k",
    "tb":                       "boiling_temperature_at_pressure_p_k",
    "normal boiling point":     "normal_boiling_temperature_k",
    "nbp":                      "normal_boiling_temperature_k",
    "normal boiling temperature": "normal_boiling_temperature_k",
    "melting point":            "normal_melting_temperature_k",
    "melting temperature":      "normal_melting_temperature_k",
    "tm":                       "normal_melting_temperature_k",
    "fusion temperature":       "normal_melting_temperature_k",
    "sle temperature":          "solidliquid_equilibrium_temperature_k",
    "solid-liquid equilibrium": "solidliquid_equilibrium_temperature_k",
    "lle temperature":          "liquidliquid_equilibrium_temperature_k",
    "liquid-liquid equilibrium":"liquidliquid_equilibrium_temperature_k",
    "triple point":             "triple_point_temperature_k",
    "triple point temperature": "triple_point_temperature_k",
    "eutectic temperature":     "eutectic_temperature_k",
    "azeotropic temperature":   "azeotropic_temperature_k",
    "azeotropic pressure":      "azeotropic_pressure_kpa",
    "azeotrope composition":    "azeotropic_composition_mole_fraction_{DOIcomp_id}",
    "eutectic composition":     "eutectic_composition_mole_fraction_{DOIcomp_id}",
    # ── Phase transition enthalpies ──────────────────────────────
    "enthalpy of fusion":       "molar_enthalpy_of_transition_or_fusion_kj_mol",
    "heat of fusion":           "molar_enthalpy_of_transition_or_fusion_kj_mol",
    "delta_fus_h":              "molar_enthalpy_of_transition_or_fusion_kj_mol",
    "enthalpy of vaporization": "molar_enthalpy_of_vaporization_or_sublimation_kj_mol",
    "heat of vaporization":     "molar_enthalpy_of_vaporization_or_sublimation_kj_mol",
    "delta_vap_h":              "molar_enthalpy_of_vaporization_or_sublimation_kj_mol",
    "enthalpy of sublimation":  "molar_enthalpy_of_vaporization_or_sublimation_kj_mol",
    # ── Mixing / excess / solution ───────────────────────────────
    "excess enthalpy":          "excess_molar_enthalpy_molar_enthalpy_of_mixing_kj_mol",
    "enthalpy of mixing":       "excess_molar_enthalpy_molar_enthalpy_of_mixing_kj_mol",
    "hex":                      "excess_molar_enthalpy_molar_enthalpy_of_mixing_kj_mol",
    "he":                       "excess_molar_enthalpy_molar_enthalpy_of_mixing_kj_mol",
    "heat of mixing":           "excess_molar_enthalpy_molar_enthalpy_of_mixing_kj_mol",
    "enthalpy of solution":     "molar_enthalpy_of_solution_kj_mol",
    "heat of solution":         "molar_enthalpy_of_solution_kj_mol",
    "enthalpy of dilution":     "molar_enthalpy_of_dilution_kj_mol",
    "heat of dilution":         "molar_enthalpy_of_dilution_kj_mol",
    "excess gibbs energy":      "excess_molar_gibbs_energy_kj_mol",
    "gex":                      "excess_molar_gibbs_energy_kj_mol",
    "ge":                       "excess_molar_gibbs_energy_kj_mol",
    "apparent molar enthalpy":  "apparent_molar_enthalpy_kj_mol",
    "partial molar enthalpy":   "partial_molar_enthalpy_kj_mol_{DOIcomp_id}",
    # ── Activity / fugacity ──────────────────────────────────────
    "activity coefficient":     "activity_coefficient_{DOIcomp_id}",
    "gamma":                    "activity_coefficient_{DOIcomp_id}",
    "mean ionic activity coefficient": "mean_ionic_activity_coefficient_{DOIcomp_id}",
    "activity":                 "relative_activity_{DOIcomp_id}",
    "relative activity":        "relative_activity_{DOIcomp_id}",
    "fugacity coefficient":     "fugacity_coefficient_{DOIcomp_id}",
    "phi":                      "fugacity_coefficient_{DOIcomp_id}",
    "osmotic coefficient":      "osmotic_coefficient",
    # ── Composition at equilibrium ───────────────────────────────
    "mole fraction":            "mole_fraction_{DOIcomp_id}",
    "x":                        "mole_fraction_{DOIcomp_id}",
    "mass fraction":            "mass_fraction_{DOIcomp_id}",
    "w":                        "mass_fraction_{DOIcomp_id}",
    "molality":                 "molality_mol_kg_{DOIcomp_id}",
    "molarity":                 "amount_concentration_molarity_mol_dm3_{DOIcomp_id}",
    "henry constant":           "henrys_law_constant_mole_fraction_scale_kpa_{DOIcomp_id}",
    "henry's law constant":     "henrys_law_constant_mole_fraction_scale_kpa_{DOIcomp_id}",
    "kh":                       "henrys_law_constant_mole_fraction_scale_kpa_{DOIcomp_id}",
    "ostwald coefficient":      "ostwald_coefficient",
    "partial pressure":         "partial_pressure_kpa_{DOIcomp_id}",
    # ── Optical / acoustic ───────────────────────────────────────
    "refractive index":         "refractive_index_na_dline",
    "nd":                       "refractive_index_na_dline",
    "n_d":                      "refractive_index_na_dline",
    "speed of sound":           "speed_of_sound_m_s",
    "sound velocity":           "speed_of_sound_m_s",
    "u":                        "speed_of_sound_m_s",
    "surface tension":          "surface_tension_liquidgas_n_m",
    "sigma":                    "surface_tension_liquidgas_n_m",
    "interfacial tension":      "interfacial_tension_n_m",
    "ift":                      "interfacial_tension_n_m",
    "permittivity":             "relative_permittivity_at_zero_frequency",
    "dielectric constant":      "relative_permittivity_at_zero_frequency",
    "epsilon":                  "relative_permittivity_at_zero_frequency",
    # ── Critical properties ──────────────────────────────────────
    "critical temperature":     "critical_temperature_k",
    "tc":                       "critical_temperature_k",
    "critical pressure":        "critical_pressure_kpa",
    "pc":                       "critical_pressure_kpa",
    "ucst":                     "upper_consolute_temperature_k",
    "upper consolute temperature": "upper_consolute_temperature_k",
    "lcst":                     "lower_consolute_temperature_k",
    "lower consolute temperature": "lower_consolute_temperature_k",
    # ── Reaction ─────────────────────────────────────────────────
    "enthalpy of reaction":     "molar_enthalpy_of_reaction_kj_mol",
    "heat of reaction":         "molar_enthalpy_of_reaction_kj_mol",
    "delta_r_h":                "molar_enthalpy_of_reaction_kj_mol",
    "gibbs energy of reaction": "molar_gibbs_energy_of_reaction_kj_mol",
    "delta_r_g":                "molar_gibbs_energy_of_reaction_kj_mol",
    "entropy of reaction":      "molar_entropy_of_reaction_j_k_mol",
    "delta_r_s":                "molar_entropy_of_reaction_j_k_mol",
    "heat of combustion":       "specific_internal_energy_of_reaction_at_constant_volume_j_g",
    "combustion energy":        "specific_internal_energy_of_reaction_at_constant_volume_j_g",
    "equilibrium constant":     "thermodynamic_equilibrium_constant",
    "keq":                      "thermodynamic_equilibrium_constant",
    "k_eq":                     "thermodynamic_equilibrium_constant",
}

_LOOKUP: dict[str, str] = {k.lower(): v for k, v in PROP_ALIASES.items()}


def expand_prop_alias(query: str) -> str:
    """Return canonical prop_id if *query* matches a known alias,
    otherwise return the original *query* unchanged."""
    return _LOOKUP.get(query.strip().lower(), query)
